version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.16.0@sha256:8f63a17b7b90c9a375a5eecb7494cd0783a89c2b7af94b814453c0006748cd37
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - store_artifacts:
          path: test-results.xml
          prefix: tests